### ISSUE TITLE
winerror 6 the handle is invalid

### ISSUE THREAD

**Issue by pro100fila** [sensity-ai/dot#109] opened 2023-08-30 14:44 UTC
When I click "Run" using SimSwap I see a red message below the button: "Winerror 6, the handle is invalid" and nothing happens.
It works only on "faceswap cv2" mode.
I use the newest version of dot executable

**Comment by Ghassen-Chaabouni** [comment] 2023-08-31 09:52
What OS system you are using and what's the error message in the command prompt?

**Comment by pro100fila** [comment] 2023-08-31 14:36
I m using windows 11 and "Winerror 6, the handle is invalid" is the error message in the command prompt.

**Comment by Ghassen-Chaabouni** [comment] 2023-08-31 15:17
> I m using windows 11 and "Winerror 6, the handle is invalid" is the error message in the command prompt.

Can you send me the full logs in the command prompt not only the error.

**Comment by Em1tSan** [comment] 2023-10-11 14:12
It's certainly great that you removed the duplicates, but, what about a solution to this problem?

**Comment by giorgiop** [comment] 2023-10-11 14:15
@Em1tSan can you with some testing? :) this issue is hard to reproduce

**Comment by Em1tSan** [comment] 2023-10-11 14:37
> @Em1tSanМожете ли вы помочь нам с тестированием? :) эту проблему трудно воспроизвести

no problem, what do you need me to do?

**Comment by Ghassen-Chaabouni** [comment] 2023-10-11 15:25
> > @Em1tSanМожете ли вы помочь нам с тестированием? :) эту проблему трудно воспроизвести
> 
> no problem, what do you need me to do?

We made few updates like removing cupy. I will generate a new executable that you can test

**Comment by Freedzone** [comment] 2023-10-26 03:08
Did you guys publish the new Windows executable somewhere? I am having the exact same issue.
Lenovo Legion 5 with AMD Ryzen 7 5800h and NVIDIA RTX 3060, 16GB of RAM
Windows 11 Home
Python 3.11

**Comment by suomynonami** [comment] 2023-11-14 06:55
any fix for this yet i have the same issue

**Comment by Ghassen-Chaabouni** [comment] 2023-11-14 11:53
I generated a new executable. Its available [here](https://drive.google.com/file/d/1dSwxNFYafV4UmRoof59ohVWEwbTj7LfW/view).
Can someone test it and confirm if they are still having this issue or not?

**Comment by suomynonami** [comment] 2023-11-14 11:54
I'll check it out I'm just about to pass out though thanks for the quick
response bro

**Comment by suomynonami** [comment] 2023-11-14 23:44
Matplotlib is building the font cache; this may take a moment.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[WinError 6] The handle is invalid

**Comment by suomynonami** [comment] 2023-11-14 23:45
still getting the error idk if you would want to connect through anydesk
and look at what i got going on here to fix the issue. let me know

**Comment by Ghassen-Chaabouni** [comment] 2023-11-15 10:00
If this new executale didn't fix this error, then I guess we need someone that still having this issue to install dot following the instructions under [cli-installation](https://github.com/sensity-ai/dot#cli-installation). Then they will need to generate the executable following the instructions [here](https://github.com/sensity-ai/dot/blob/main/docs/create_executable.md#create-executable)

**Comment by Em1tSan** [comment] 2023-11-16 17:29
@Ghassen-Chaabouni Does the current version of the source code contain a fix or have you not published yet?

**Comment by Ghassen-Chaabouni** [comment] 2023-11-16 19:00
I published the latest executable but it seems that the issue still exist there. 
I don't expect this error to appear if you use the cli of dot instead of the executable. You will need to follow the instructions under [cli-installation](https://github.com/sensity-ai/dot#cli-installation).

**Comment by kaelkorolevskiy** [comment] 2023-11-16 22:30
> e

![image](https://github.com/sensity-ai/dot/assets/94924739/541ad5be-0d1c-435c-bf66-f8b6363b1aa6)
basically what happens when you try running 
dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu (it's for both with --use_gpu and without). program connects to the webcam and then crashes itself.

**Comment by kaelkorolevskiy** [comment] 2023-11-16 22:30
> > e
> 
> ![image](https://user-images.githubusercontent.com/94924739/283614086-541ad5be-0d1c-435c-bf66-f8b6363b1aa6.png) basically what happens when you try running dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu (it's for both with --use_gpu and without). program connects to the webcam and then crashes itself.

i tried to recreate this issue on the linux, seems like it's windows based problem only

**Comment by kaelkorolevskiy** [comment] 2023-11-17 21:34
> > > > e
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/94924739/283614086-541ad5be-0d1c-435c-bf66-f8b6363b1aa6.png) basically what happens when you try running dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu (it's for both with --use_gpu and without). program connects to the webcam and then crashes itself.
> > 
> > 
> > i tried to recreate this issue on the linux, seems like it's windows based problem only
> 
> My guess is that maybe you are running out of GPU memory. Can you confirm if this the case or not by checking nvidia-smi?

i've got rtx 4070 ti, 16gb. launch barely makes any impact on gpu memory . it just crashes instantly (running on cpu makes no difference)

**Comment by Ghassen-Chaabouni** [comment] 2023-11-21 13:32
> > > > > e
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/94924739/283614086-541ad5be-0d1c-435c-bf66-f8b6363b1aa6.png) basically what happens when you try running dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu (it's for both with --use_gpu and without). program connects to the webcam and then crashes itself.
> > > 
> > > 
> > > i tried to recreate this issue on the linux, seems like it's windows based problem only
> > 
> > 
> > My guess is that maybe you are running out of GPU memory. Can you confirm if this the case or not by checking nvidia-smi?
> 
> i've got rtx 4070 ti, 16gb. launch barely makes any impact on gpu memory . it just crashes instantly (running on cpu makes no difference)

Can you run dot on images without a webcam and check if you get the results under `test_local` by running this command 
`dot -c ./configs/simswap.yaml --target data/ --source "data/" --save_folder test_local/ --use_image --use_gpu`
Also send me more information about your OS and machine. I will try to reproduce this issue.

**Comment by maxmelichov** [comment] 2023-12-26 12:06
any updates?

**Comment by Ghassen-Chaabouni** [comment] 2023-12-27 09:44
> any updates?

Are you also getting this error? If so, what python version are you using?

**Comment by Ghassen-Chaabouni** [comment] 2023-12-27 09:48
> > any updates?
> 
> Are you also getting this error? If so, what python version are you using? DOT was tested with python 3.8

Also can you share info about your OS

**Comment by bmleeBigby** [comment] 2023-12-28 10:41
> > > > > > e
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/94924739/283614086-541ad5be-0d1c-435c-bf66-f8b6363b1aa6.png) basically what happens when you try running dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu (it's for both with --use_gpu and without). program connects to the webcam and then crashes itself.
> > > > 
> > > > 
> > > > i tried to recreate this issue on the linux, seems like it's windows based problem only
> > > 
> > > 
> > > My guess is that maybe you are running out of GPU memory. Can you confirm if this the case or not by checking nvidia-smi?
> > 
> > 
> > i've got rtx 4070 ti, 16gb. launch barely makes any impact on gpu memory . it just crashes instantly (running on cpu makes no difference)
> 
> Can you run dot on images without a webcam and check if you get the results under `test_local` by running this command `dot -c ./configs/simswap.yaml --target data/ --source "data/" --save_folder test_local/ --use_image --use_gpu` Also send me more information about your OS and machine. I will try to reproduce this issue.

Same problem on my side

I tried running both the executable, and the CLI version from scratch. Both crashed except for cv2 in executable version
Replicated the CLI build using conda, python 3.8, same version on cuda, torch, etc. Changing between CPU and GPU use is not resulting in anything.

Executable version error : Winerror 6, the handle is invalid

CLI version error : INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
besides that nothing really, after it turns on the camera for a couple seconds it just stops

Windows 11
16gb ram
11th gen INtel i9-11900H
RTX 3060

Help resolving this issue is appreciated, thanks in advance.

**Comment by Ghassen-Chaabouni** [comment] 2023-12-28 13:10
Could someone experiencing this problem and having the CLI set up, kindly assists in debugging? I would like to know in which line of code this error is occurring.

**Comment by bmleeBigby** [comment] 2023-12-28 13:21
> Could someone experiencing this problem and having the CLI set up, kindly assists in debugging? I would like to know in which line of code this error is occurring.

what do I need to do? 

I have to say beforehand that I have a slight different installation process where I install the dlib dependency using conda instead of pip, since it kept failing due to cmake. But was able to get dot installed fine in the end.

**Comment by Ghassen-Chaabouni** [comment] 2023-12-28 13:35
> > Could someone experiencing this problem and having the CLI set up, kindly assists in debugging? I would like to know in which line of code this error is occurring.
> 
> what do I need to do?
> 
> I have to say beforehand that I have a slight different installation process where I install the dlib dependency using conda instead of pip, since it kept failing due to cmake. But was able to get dot installed fine in the end.

A simple debugging is to add some print statements at different points in the code until you locate the line that has the error.
You can also catch the exception and trace the error

**Comment by bmleeBigby** [comment] 2023-12-28 13:46
> > > Could someone experiencing this problem and having the CLI set up, kindly assists in debugging? I would like to know in which line of code this error is occurring.
> > 
> > 
> > what do I need to do?
> > I have to say beforehand that I have a slight different installation process where I install the dlib dependency using conda instead of pip, since it kept failing due to cmake. But was able to get dot installed fine in the end.
> 
> A simple debugging is to add some print statements at different points in the code until you locate the line that has the error. You can also catch the exception and trace the error

Could you send me files edited with print statements in whichever point you suspect to be the issue? So I can overwrite my local installation files and help run it without having to trace the program flow from scratch.

**Comment by Ghassen-Chaabouni** [comment] 2023-12-28 13:56
> Could you send me files edited with print statements in whichever point you suspect to be the issue?

I'm not sure what file is causing the issue as I'm still not able to reproduce it so I don't know where to put the prints

**Comment by Ghassen-Chaabouni** [comment] 2023-12-28 16:25
@bmleeBigby By the way, just to confirm, did you install the required C++ packages from `Visual Studio` ?

> i. Download and install Visual Studio Community from [here](https://visualstudio.microsoft.com/vs/community/)
> ii. Install Desktop development with C++ from the Visual studio installer

**Comment by bmleeBigby** [comment] 2023-12-29 06:05
> @bmleeBigby By the way, just to confirm, did you install the required C++ packages from `Visual Studio` ?
> 
> > i. Download and install Visual Studio Community from [here](https://visualstudio.microsoft.com/vs/community/)
> > ii. Install Desktop development with C++ from the Visual studio installer

Yes I believe I've installed it please check below
![image](https://github.com/sensity-ai/dot/assets/66548262/b4859e36-046f-4dfc-903f-0d71cc7abab8)

However in my case, I changed the dlib to be installed from Conda instead of PIP, because I keep having error "CMake must be installed to build the following extensions: dlib" even after installing the CMake manually and set as PATH. Hope it's not an issue since the DOT installation was successful anyway.
![image](https://github.com/sensity-ai/dot/assets/66548262/68ce2471-762d-4fae-8fc6-c72b5738c51e)

**Comment by Ghassen-Chaabouni** [comment] 2023-12-29 21:01
@bmleeBigby I generated an executable that can be used to trace the error. Try to download it from [here](https://drive.google.com/file/d/1GSgkgCsfJfm7I6jXXjrFYplKdhZhimvt/view) and run it. It should print the error message. Once you get it, paste it in this issue

**Comment by bmleeBigby** [comment] 2024-01-02 07:11
> @bmleeBigby I generated an executable that can be used to trace the error. Try to download it from [here](https://drive.google.com/file/d/1GSgkgCsfJfm7I6jXXjrFYplKdhZhimvt/view) and run it. It should print the error message. Once you get it, paste it in this issue. If you want to use the CLI, this PR #137 added the tracing to it.

Pardon the delay during holiday

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "dot\__main__.py", line 69, in run
  File "dot\dot.py", line 131, in generate
  File "dot\commons\model_option.py", line 184, in generate_from_camera
  File "dot\simswap\option.py", line 83, in create_model
  File "dot\simswap\parsing_model\model.py", line 198, in __init__
  File "dot\simswap\parsing_model\model.py", line 99, in __init__
  File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
  File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
  File "torch\hub.py", line 741, in load_state_dict_from_url
    sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
OSError: [WinError 6] The handle is invalid
```

**Comment by Ghassen-Chaabouni** [comment] 2024-01-02 10:37
> > @bmleeBigby I generated an executable that can be used to trace the error. Try to download it from [here](https://drive.google.com/file/d/1GSgkgCsfJfm7I6jXXjrFYplKdhZhimvt/view) and run it. It should print the error message. Once you get it, paste it in this issue. If you want to use the CLI, this PR #137 added the tracing to it.
> 
> Pardon the delay during holiday
> 
> ```
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> Traceback (most recent call last):
>   File "dot\__main__.py", line 69, in run
>   File "dot\dot.py", line 131, in generate
>   File "dot\commons\model_option.py", line 184, in generate_from_camera
>   File "dot\simswap\option.py", line 83, in create_model
>   File "dot\simswap\parsing_model\model.py", line 198, in __init__
>   File "dot\simswap\parsing_model\model.py", line 99, in __init__
>   File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
>   File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
>   File "torch\hub.py", line 741, in load_state_dict_from_url
>     sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
> OSError: [WinError 6] The handle is invalid
> ```

It seems that it's not able to download the resnet model. I generated another executable after I downloaded that model and put it in `saved_models/simswap` with other changes. Can you test this new version. It's available [here](https://drive.google.com/file/d/17jrZbwbupOixo2xxUW4R19pR39gYzgJS)

**Comment by bmleeBigby** [comment] 2024-01-03 06:45
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "dot\__main__.py", line 69, in run
  File "dot\dot.py", line 131, in generate
  File "dot\commons\model_option.py", line 184, in generate_from_camera
  File "dot\simswap\option.py", line 83, in create_model
  File "dot\simswap\parsing_model\model.py", line 198, in __init__
  File "dot\simswap\parsing_model\model.py", line 99, in __init__
  File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
  File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
  File "torch\hub.py", line 741, in load_state_dict_from_url
    sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
OSError: [WinError 6] The handle is invalid

Traceback (most recent call last):
  File "dot\__main__.py", line 69, in run
  File "dot\dot.py", line 131, in generate
  File "dot\commons\model_option.py", line 184, in generate_from_camera
  File "dot\simswap\option.py", line 83, in create_model
  File "dot\simswap\parsing_model\model.py", line 198, in __init__
  File "dot\simswap\parsing_model\model.py", line 99, in __init__
  File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
  File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
  File "torch\hub.py", line 741, in load_state_dict_from_url
    sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
OSError: [WinError 6] The handle is invalid
```

Error remains the same, using simswap, and simswap config file

2nd Error when I attempt to manually set the model_path into the resnet18-5c106cde.pth

**Comment by Ghassen-Chaabouni** [comment] 2024-01-03 09:55
> ```
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> Traceback (most recent call last):
>   File "dot\__main__.py", line 69, in run
>   File "dot\dot.py", line 131, in generate
>   File "dot\commons\model_option.py", line 184, in generate_from_camera
>   File "dot\simswap\option.py", line 83, in create_model
>   File "dot\simswap\parsing_model\model.py", line 198, in __init__
>   File "dot\simswap\parsing_model\model.py", line 99, in __init__
>   File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
>   File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
>   File "torch\hub.py", line 741, in load_state_dict_from_url
>     sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
> OSError: [WinError 6] The handle is invalid
> 
> Traceback (most recent call last):
>   File "dot\__main__.py", line 69, in run
>   File "dot\dot.py", line 131, in generate
>   File "dot\commons\model_option.py", line 184, in generate_from_camera
>   File "dot\simswap\option.py", line 83, in create_model
>   File "dot\simswap\parsing_model\model.py", line 198, in __init__
>   File "dot\simswap\parsing_model\model.py", line 99, in __init__
>   File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
>   File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
>   File "torch\hub.py", line 741, in load_state_dict_from_url
>     sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
> OSError: [WinError 6] The handle is invalid
> ```
> 
> Error remains the same, using simswap, and simswap config file
> 
> 2nd Error when I attempt to manually set the model_path into the resnet18-5c106cde.pth

I removed the usage of `load_state_dict_from_url` as it appears to cause this error. The new executable is [here](https://drive.google.com/file/d/10LXgtE721YPXdHfzcDUp6ba-9klueocR/view). Let me know if the error still appears.

**Comment by bmleeBigby** [comment] 2024-01-04 06:36
> > ```
> > INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> > Traceback (most recent call last):
> >   File "dot\__main__.py", line 69, in run
> >   File "dot\dot.py", line 131, in generate
> >   File "dot\commons\model_option.py", line 184, in generate_from_camera
> >   File "dot\simswap\option.py", line 83, in create_model
> >   File "dot\simswap\parsing_model\model.py", line 198, in __init__
> >   File "dot\simswap\parsing_model\model.py", line 99, in __init__
> >   File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
> >   File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
> >   File "torch\hub.py", line 741, in load_state_dict_from_url
> >     sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
> > OSError: [WinError 6] The handle is invalid
> > 
> > Traceback (most recent call last):
> >   File "dot\__main__.py", line 69, in run
> >   File "dot\dot.py", line 131, in generate
> >   File "dot\commons\model_option.py", line 184, in generate_from_camera
> >   File "dot\simswap\option.py", line 83, in create_model
> >   File "dot\simswap\parsing_model\model.py", line 198, in __init__
> >   File "dot\simswap\parsing_model\model.py", line 99, in __init__
> >   File "dot\simswap\parsing_model\resnet.py", line 66, in __init__
> >   File "dot\simswap\parsing_model\resnet.py", line 80, in init_weight
> >   File "torch\hub.py", line 741, in load_state_dict_from_url
> >     sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
> > OSError: [WinError 6] The handle is invalid
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error remains the same, using simswap, and simswap config file
> > 2nd Error when I attempt to manually set the model_path into the resnet18-5c106cde.pth
> 
> I removed the usage of `load_state_dict_from_url` as it appears to cause this error. The new executable is [here](https://drive.google.com/file/d/10LXgtE721YPXdHfzcDUp6ba-9klueocR/view). Let me know if the error still there.

Issue resolved !

**Comment by Ghassen-Chaabouni** [comment] 2024-01-04 08:31
@bmleeBigby Thanks for your help. I pushed this fix to main.

**Comment by Ghassen-Chaabouni** [comment] 2024-01-05 14:44
Can anyone else that used to get this error download the latest executable from [here](https://drive.google.com/file/d/10LXgtE721YPXdHfzcDUp6ba-9klueocR/view) and confirm that DOT is working fine?

**Comment by giorgiop** [comment] 2024-01-09 21:25
I am closing for inactivity. If folks are still experiencing this issue, please reopen

**Closed by giorgiop** 2024-01-09 21:25 UTC
Labels: bug
