### ISSUE TITLE
WinError 6 The handle is invalid

### ISSUE THREAD

**Issue by xlo-u** [sensity-ai/dot#111] opened 2023-09-15 12:57 UTC
Showing the error  [WinError 6] The handle is invalid

It's issue in a tool or i make mistake please let me know
    thanks
![Screenshot 2023-09-15 182204](https://github.com/sensity-ai/dot/assets/67045160/a754346d-d0b8-45f6-98a8-145cfdefdb83)

**Comment by giorgiop** [comment] 2023-09-15 13:01
Hi @xloyash , can you share more about the system you are running this on?

**Comment by xloyash** [comment] 2023-09-15 16:34
OPERATING SYSTEM 
Microsoft Windows 11 Home Single Language 
- Release ID: 2009 
- Version: 10.0.22621 
- Build: 22621 
CPU 
AMD Ryzen 5 5600H with Radeon Graphics          
- Clock speed: 3301MHz 
- Description: AMD64 Family 25 Model 80 Stepping 0 
GPU 
NVIDIA GeForce GTX 1650 
- Driver version: 30.0.15.1278 
AMD Radeon(TM) Graphics 
- Refresh rate: 60Hz 
- Driver version: 31.0.12044.3

**Comment by Ghassen-Chaabouni** [comment] 2023-09-15 18:01
@xloyash you may be running out of memory. Can you close all other open applications and try running dot again?

**Comment by xloyash** [comment] 2023-09-15 19:53
Done sir , i don't know why still its showing same error

**Comment by Em1tSan** [comment] 2023-10-05 21:18
I suddenly encountered this error today too, windows 11, RTX 4090

**Comment by giorgiop** [comment] 2023-10-11 11:51
duplicate of https://github.com/sensity-ai/dot/issues/109

**Closed by giorgiop** 2023-10-11 11:51 UTC
Labels: question
