### ISSUE TITLE
WinError 6 The handle is invalid - On all launch options

### ISSUE THREAD

**Issue by Em1tSan** [sensity-ai/dot#125] opened 2023-10-07 00:52 UTC
## :bug: Bug Report

This error occurs both on a freshly downloaded version and on a self-compiled version. There is minimal information in the logs.

My system:
Windows 11 Pro 22631.2338
Nvidia RTX 4090 Driver 537.42

![image](https://github.com/sensity-ai/dot/assets/70670181/ddad04e4-97dd-407c-a885-9ed21e5934c5)
![image](https://github.com/sensity-ai/dot/assets/70670181/289f17cc-838f-46cd-8c74-9a8d74c905a5)

**Comment by giorgiop** [comment] 2023-10-11 11:51
duplicate of https://github.com/sensity-ai/dot/issues/109

**Closed by giorgiop** 2023-10-11 11:51 UTC
Labels: bug
